version: "3"
services:
  pg_master:
    build: ./master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hamed
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hamed
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    networks:
      default:
        aliases:
          - pg_cluster
    ports:
      - 5442:5432 
  pg_slave:
    build: ./slave
    environment:
      - POSTGRES_USER=hamed
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hamed
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
      - PG_MASTER_HOST=pg_master
    networks:
      default:
        aliases:
          - pg_cluster
    ports:
      - 5443:5432 
volumes:
  pg_data: